GET http://localhost:3003/api/books/
### 
GET http://localhost:3003/api/books/638494d557641ab9279b9995
###
POST http://localhost:3003/api/books/
Content-Type: application/json

{
"title": "zxc",
"author": "miika",
"genre": "fantasy"
}
###
PUT http://localhost:3003/api/books/63872e2a4f2f46922e1133bf
Content-Type: application/json

{
"loanStatus": false
}
###
DELETE http://localhost:3003/api/books/638dcd0ea78100ef0a6c3ce2