GET http://localhost:3003/api/books/
### 
GET http://localhost:3003/api/books/638494d557641ab9279b9995
###
POST http://localhost:3003/api/books/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoiNjM5MWMxODllNGI1M2UyMWVjNzRjM2YwIiwiYWRtaW4iOnRydWUsImlhdCI6MTY3MDUwMzkyMn0.h_QSa8myuuLqC8605HcgbRU29Z15Yer9nokKc5znns4

{
"title": "test4",
"author": "tester",
"genre": "test"
}
###
PUT http://localhost:3003/api/books/63872e2a4f2f46922e1133bf
Content-Type: application/json

{
"loanStatus": false
}
###
DELETE http://localhost:3003/api/books/638dcd0ea78100ef0a6c3ce2