POST http://localhost:3003/api/users HTTP/1.1 
Content-Type: application/json

{
"email": "qwe@gmail.com",
"password": "password123"
}

###

GET http://localhost:3003/api/users HTTP/1.1 


###

DELETE http://localhost:3003/api/users/6390746bfc719779f63d9559